### ISSUE TITLE
Ownership of pointers

### ISSUE THREAD

**Issue by Gavazzi1** [ricardolarios/A1-part2#15]
Who owns the pointer to an object passed to enqueue()?

This is creating some issues for us because if the Queue owns the pointers, then it needs to free them, but the tests pass references to statically declared Objects, which are automatically freed when they go out of scope. The result is a `double free or corruption` error.

**Comment by KyleCrampton** [comment]
We believe the Queue should own them. Thanks for catching this. Honestly we didn't allocate objects on the heap in the tests because we're lazy and didn't want to have to delete them. We'll update the tests to reflect this.

**Comment by KyleCrampton** [comment]
Should be fixed. Let us know if you encounter any more issues.

**Comment by Gavazzi1** [comment]
I think there's one last issue.

In the tests, you delete `removed_elem`, then enqueue `elem_1` later on, but those two Objects are equal, so we get a segfault trying to free `elem_1` in the deconstructor.

**Comment by ricardolarios** [comment]
Oops, just removed that line since the test enqueues it again later. Hopefully should be all set now!

**Comment by ricardolarios** [comment]
So after talking it over a bit more, and after [PR 17](https://github.com/ricardolarios/A1-part2/pull/17), we decided to contradict what we told you here and say that the Queue should NOT own it's objects and be responsible for their memory, and instead the memory will still be managed by the original object and will have to be deleted separately. We'll update the test file soon to reflect that within the original tests. Sorry to be annoying!
