### ISSUE TITLE
Still a few pointer ownership issues

### ISSUE THREAD

**Issue by Gavazzi1** [ricardolarios/A1-part2#19]
In the test case bodies, some objects are freed when they are still owned by the Queue. For example, in test_enqueue_dequeue(), you delete s1 and s2 when they are still in the Queue

**Comment by KyleCrampton** [comment]
After [this commit](https://github.com/ricardolarios/A1-part2/commit/7aa6e580e90d88615b2fa821b459ec1385dbf2b7), the current test cases should be deleting the Queue before deleting the strings it stores. Is there a specific line you're referring to?

**Comment by Gavazzi1** [comment]
Sorry, you're right that they're not deleted while they're in the queue. But, since the queue owns the pointers, you shouldn't delete the strings after the queue since the queue just deleted them

**Comment by ricardolarios** [comment]
Yeah sorry about that! We mentioned in [issue 15](https://github.com/ricardolarios/A1-part2/issues/15) that we talked it over a bit more and decided it made more sense to NOT have the Queue handle the memory of what it stores. Hopefully that clears up the confusion!

**Comment by Gavazzi1** [comment]
Oh oops. Sorry I missed that. Thanks for the clarification!
