### ISSUE TITLE
Remove methods and constructor related to max_size

### ISSUE THREAD

**Issue by aperez809** [ricardolarios/A1-part2#5]
Because these data structures should to be "insanely scalable" per the assignment spec, we don't think it makes sense to set any limitations on the size of the Queue. That means the constructor with a `max_size` argument, the getter method for `max_size`, and the `is_full()` method should be removed. Our implementation is using two stacks to simulate the operations of a Queue, so we will be implementing `is_full()` there instead of in the Queue class.

**Comment by ricardolarios** [comment]
Good points, I agree! I'll remove those in a minute and leave the default constructor and let the implementation deal with handling size issues.
