### ISSUE TITLE
Max Size & Is-Full Function

### ISSUE THREAD

**Issue by elehman16** [ricardolarios/A1-part2#7]
In line 16 and line 36 of the test file, there is a max_size function: assert(test_queue.max_size() == max_size) and assert(test_queue.is_full()). 

I saw that there was another issue where you guys decided to remove it. Would it be possible for you to either add this functionally back into the method stubs or rather remove this test case? Thanks!!

**Comment by KyleCrampton** [comment]
Removed the tests and also the constructors that took in max_size.
