### ISSUE TITLE
String Init in test-queue.cpp

### ISSUE THREAD

**Issue by elehman16** [ricardolarios/A1-part2#8]
We noticed in the test file that String examples were initialized as String(). Could these be changed to take in character arrays such as String("")? It's a small feature, but it would help us out and would line up with the String class constructors presented in: https://piazza.com/class/k51bluky59n2jr?cid=166.

**Comment by KyleCrampton** [comment]
We already have constructors for Strings which take in chars in the String class, but I went ahead and added some tests that use Strings with passed in chars!
